Feature/OT174 26 Middleware for authenticated users
alkemyTech/OT174-server pull request #14
Opened 2022-04-19 17:12 UTC by javicara

# Description
The goal of the function is verify if the token provided in the request it's valid, otherwise the response will be invalid with a 400 state

# Criterios de aceptación:

- [ ] Deberá chequear si la petición contiene el token correspondiente a un usuario, caso contrario deberá devolver un código de error 403 con un mensaje de error.

2022-04-20 21:47 UTC, edgarsilvalovera commented on middlewares/authMiddleware.js
> +        console.log(verify);
por qué un console.log?

2022-04-20 21:48 UTC, edgarsilvalovera requested changes
- Sustituya verify por validate
- Mejore la responsabilidad del método verify

2022-04-21 14:03 UTC, javicara commented on middlewares/authMiddleware.js
> +        console.log(verify);
Upsss se me paso jaja

2022-04-25 18:56 UTC, edgarsilvalovera approved these changes

2022-05-10 00:41 UTC, merged