Feature/ot174 24
alkemyTech/OT174-server pull request #15
Opened 2022-04-20 14:47 UTC by yego0210

2022-04-20 14:49 UTC, yego0210 commented
tarea 24 endepoint de registro

2022-04-20 21:49 UTC, edgarsilvalovera commented on .env.example
> +DB_NAME=ong
por qué hace cambios en este .env

2022-04-20 21:49 UTC, edgarsilvalovera commented on .gitignore
>  .env
por qué modifica el .gitignore?

2022-04-20 21:50 UTC, edgarsilvalovera commented on .vscode/settings.json
> +{
para qué hace commit de este archivo?

2022-04-20 21:52 UTC, edgarsilvalovera requested changes
- La nomenclatura de los métodos es en ingles y camelCase; ejemplo createUser, getUserById, deleteUserById, 
- Mejore la responsabilidad del méotdo AddUsuario.
- Aplique async, await

NOta: el código debe estar escrito en ingles, use nomenclatura camelCase para los nombres de los archivos

2022-04-20 22:02 UTC, yego0210 commented on .vscode/settings.json
> +{
lo que pasa profe es que le hice commit al proyecto en vsc , entonces le doy commit a todo lo que aparece hay

2022-04-21 22:11 UTC, yego0210 commented
no entiendo esto

2022-04-21 22:24 UTC, closed without merging