Feacture/ot174 30
alkemyTech/OT174-server pull request #17
Opened 2022-04-20 14:52 UTC by yego0210

2022-04-20 21:59 UTC, edgarsilvalovera requested changes
Mejore la implementación del envío de email, el méotdo sólo debe recibir el campo email, y el html de la plantilla debe obtenerse en una variable o const

2022-04-20 21:59 UTC, edgarsilvalovera commented on helpers/plantillaEmail.js
> +const sendEmail = (email, nombre, lastName) => {
solo debe recibir el email

2022-04-20 21:59 UTC, edgarsilvalovera commented on helpers/plantillaEmail.js
> +    html: `
esta plantilla debera obtenerla de una variable o const

2022-04-20 22:01 UTC, edgarsilvalovera commented on config/config.js
> +        "SENDGRID_API_KEY": process.env.SENDGRID_API_KEY,
por qué declara estas variables en este archivo de config?

2022-04-20 22:02 UTC, edgarsilvalovera requested changes
Mejore la implementación. El código debe ir en inglés

2022-04-21 23:48 UTC, yego0210 commented on helpers/plantillaEmail.js
> +    html: `
resuelto

2022-04-21 23:48 UTC, yego0210 commented on helpers/plantillaEmail.js
> +const sendEmail = (email, nombre, lastName) => {
Resuelto

2022-04-22 00:00 UTC, yego0210 reviewed
ok

2023-02-28 08:10 UTC, closed without merging